version: "3"

services:
  app:
    container_name: hexlet-app
    command: bash -c "npm test"
    build:
      context: .
      dockerfile: Dockerfile.production
    depends_on:
      - db

  db:
    container_name: hexlet-db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres