version: "3"

services:
  app:
    container_name: hexlet-app
    command: bash -c "npm test"
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      DATABASE_NAME: postgres
      DATABASE_USERNAME:  postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: db
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: hexlet-db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"
      timeout: 2s