version: "3"


services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    command: npm run dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/app