version: "3"

services:
  app:
    container_name: hexlet-app
    command: bash -c "npm test"
    build:
      context: .
      dockerfile: Dockerfile.production
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: hexlet-db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"
      timeout: 2s