version: "3"


services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile

  app:
    command: bash -c "npm run dev"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME:  ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: 5432
      DATABASE_HOST: db
    ports:
      - 8080:8080
    volumes:
      - ./app:/app