FROM node:14.21.3-slim

RUN apt-get update -y && apt-get upgrade -y && apt-get install -yq make

WORKDIR /app

COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm ci

COPY app/. .

EXPOSE 8080

CMD npm start